apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: iansilvasptech/gateway
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKey:
                  name: microservices-configmap
                  key: GATEWAY_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKey:
                  name: microservices-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKey:
                  name: microservices-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKey:
                  name: microservices-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name:
              valueFrom:
                configMapKey:
                  name: microservices-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
